name: Vue + Tauri

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install glib dependencies
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev libgirepository1.0-dev

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install project dependencies
        run: |
          pnpm install

      - name: Build Vue frontend
        run: |
          pnpm build

      - name: Build Tauri application
        run: |
          pnpm tauri build
